import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{auth,provider,signInWithPopup,signOut}from'./firebase';
import{onAuthStateChanged}from'firebase/auth';
import'./style.css';

const API=import.meta.env.VITE_API_URL||'';
async function api(path,token,body){const r=await fetch(`${API}${path}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d;}
function App(){
 const[user,setUser]=useState(null),[q,setQ]=useState(''),[a,setA]=useState([]),[notes,setNotes]=useState([]),[busy,setBusy]=useState(false),[err,setErr]=useState('');
 useEffect(()=>onAuthStateChanged(auth,setUser),[]);
 async function login(){setErr('');try{await signInWithPopup(auth,provider)}catch(e){setErr(e.message)}}
 async function send(){if(!q.trim()||!user)return;setBusy(true);setErr('');const text=q.trim();const next=[...a,{role:'user',text}];setA(next);setQ('');try{const token=await user.getIdToken();const r=await api('/api/chat',token,{messages:next});setA(v=>[...v,{role:'model',text:r.text}])}catch(e){setErr(e.message)}finally{setBusy(false)}}
 async function summarize(){if(!a.length)return;setBusy(true);try{const token=await user.getIdToken();const r=await api('/api/summarize',token,{messages:a});setNotes(v=>[r,...v])}catch(e){setErr(e.message)}finally{setBusy(false)}}
 return <div className="app"><header><div><b>✦ Personal Gemini Journal</b><span>Private thinking space</span></div>{user?<button onClick={()=>signOut(auth)}>Sign out</button>:<button onClick={login}>Sign in with Google</button>}</header><main><section className="hero"><p className="eyebrow">GEN AI ACADEMY · IDEATHON</p><h1>Think clearly.<br/><i>Keep what matters.</i></h1><p>Authenticated journaling, Gemini brainstorming, private Firestore storage, and automatic insights.</p></section>{!user?<div className="login card"><h2>Your private journal starts with sign-in.</h2><p>Google Authentication creates your user boundary before any journal data is stored.</p><button onClick={login}>Continue with Google →</button></div>:<div className="grid"><section className="card"><div className="title"><h2>Gemini conversation</h2><span>● {user.email}</span></div><div className="chat">{a.length?a.map((x,i)=><div className={x.role==='user'?'msg you':'msg'} key={i}><small>{x.role==='user'?'You':'Gemini'}</small><p>{x.text}</p></div>):<div className="empty">Start with a thought, question, goal, or idea.</div>}</div><div className="composer"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="What’s on your mind?" disabled={busy}/><button onClick={send} disabled={busy}>{busy?'Thinking…':'Send ↗'}</button></div>{a.length>1&&<button className="save" onClick={summarize} disabled={busy}>Create secure summary + next actions</button>}</section><section className="card journal"><div className="title"><h2>Saved insights</h2><span>Owner only</span></div>{notes.length?notes.map(n=><article key={n.id}><h3>{n.title}</h3><p>{n.summary}</p>{n.nextActions?.length>0&&<ul>{n.nextActions.map((x,i)=><li key={i}>{x}</li>)}</ul>}</article>):<div className="empty">Your Gemini summaries and next actions will appear here.</div>}</section></div>}{err&&<div className="error">{err}</div>}<section className="features"><div><b>01 · Authenticated</b><p>Firebase Authentication establishes the user identity.</p></div><div><b>02 · Isolated</b><p>Firestore records live under users/{'{uid}'}/journals.</p></div><div><b>03 · Protected</b><p>Gemini API credentials are read server-side from Secret Manager.</p></div><div><b>04 · Insight Loop</b><p>Every conversation can become structured insights and next actions.</p></div></section></main><footer>Security-first production implementation · Gemini + Firebase</footer></div>}
createRoot(document.getElementById('root')).render(<App/>);